import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "@/app/globals.css";

import { Toaster } from 'react-hot-toast';
import LayoutShell from "@/components/LayoutShell";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Frontend Prueba Técnica JAKAY",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-slate-200 text-gray-950`}>
        <Toaster position="top-right" />
        <LayoutShell>
            {children}
        </LayoutShell>
        </body>
        </html>
    );
}
